### ISSUE TITLE
Spike: Physical Activity threshold vs. learned cut points

### ISSUE THREAD

**Issue by Asanto32** [childmindresearch/wristpy#10]
### Description

Currently, threshold for physical activity levels are hardcoded into GGIR for each analysis. We should add option for multiple methods: cut-point thresholds as GGIR, learned levels based on individual level activity (deep learning or regression based on daily/weekly ranges of activity), use HR/other features?

### Tasks

- [ ] Task 1

**Comment by ReinderVosDeWael** [comment]
Reclassifiede to spike, time box is: 5 days.

**Comment by frey-perez** [comment]
Following the conclusion of the spike It was determined that  in order to proceed it was critical to have access to accelerometer data which was synchronized to some measure of energy expenditure (e.g. VO2, METs etc). However we don't currently have easy access to such data internally. Furthermore providing these thresholds is not critical to the core function of the package, and so the spike will be closed.
